<?php
include_once $_SERVER ['DOCUMENT_ROOT'] . "/config.php";

include_once $INCLUDE_PATH.'/sql/customer.php';
include_once $INCLUDE_PATH.'/sql/tn.php';

// get customer list
$kunden = sql_getCustomers();

// get tn List
$tns = sql_getTns();


//get active TNs and create JSON Object to handle active TNs
$activeTns = sql_getActiveTns();


$activeTnArray = array();
foreach ( $activeTns as $tn ) {
	$activeTnArray[] = json_encode($tn);
}

?>
<html>

<head>
<title>Tn Manager</title>
<!--  LIBS -->
<script type="text/javascript" src="js/lib/jquery-2.0.3.min.js"></script>
<script type="text/javascript" src="js/lib/jquery-ui-1.10.3.custom.min.js"></script>
<script type="text/javascript" src="js/lib/datetimepicker-master/jquery.datetimepicker.js"></script>
<script type="text/javascript" src="js/lib/moment.js"></script>
<script type="text/javascript" src="js/lib/functions.js"></script>

<!--  CUSTOM -->
<script type="text/javascript" src="js/ajaxFunctions.php"></script>
<script type="text/javascript" src="js/tnCustomer.js"></script>
<script type="text/javascript" src="js/tnEditTable.js"></script>
<script type="text/javascript" src="js/tnSummary.js"></script>
<script type="text/javascript" src="js/tnManager.js"></script>
<script type="text/javascript" src="js/tnActiveHandler.js"></script>
<script type="text/javascript" src="js/tnTimeEditor.js"></script>

<link rel="stylesheet" href="css/styles.css" />
<link rel="stylesheet"
	href="css/ui-lightness/jquery-ui-1.10.3.custom.min.css">
<link rel="stylesheet" href="js/lib/datetimepicker-master/jquery.datetimepicker.css" />
</head>
<body>

	<h1>TN Manager 1.4.1</h1>
	<div id="outer">

	<div id="options" class="container">
		<!--  CUSTOMER LIST -->
		<h2>Kunden: </h2>
		<div id="customers">
			<?php
				foreach ( $kunden as $k ) {
					echo "<div class='tn_customer' data-customer_name='". $k ["name"] ."' data-customer_id='". $k ["id"] ."' >
							<span>" . $k ["name"] . "</span>
						  </div>";
				}
			?>
		</div>
		<!--  END CUSTOMER LIST -->
		
		<!-- Add new row button and textfield -->
		<input type="text" id="new_cust_name" placeholder="Kundenname" />
		<br/>
		<span id="customer-add-hint"></span>
		<input type="button" id="new_cust_btn" 
			value="Neue Position + TN" />
	</div>
	
	<div id="currentTable" class="container">
		<h2>Aktuell:</h2>
		<table id="TNs">
			<tr>
				<th class="idColumn">ID</th>
				<th class="actionColumn">Aktion</th>
				<th class="customerColumn">Kunde</th>
				<th class="tatColumn">T&auml;tigkeit</th>
				<th class="timeColumn">Zeit</th>
				<th >Gerundete Stunden</th>
			</tr>
			<!-- Additional Rows are generated by JS when using the "add" button -->
		</table>
		
	</div>
	<div class="clear"></div>
	<br />
	<hr>
	<br />
	<div id="summaryContainer" class="container">
		<h2>Zusammenfassung</h2>
		<table id="summary">
			<tr>
				<th>Kunde</th>
				<th>TN_ID</th>
				<th>TN Text</th>
				<th>Datum</th>
				<th>Zeit</th>
				<th>Aktion</th>
			</tr>
	<?php
	
	foreach ( $tns as $tn ) {
		

		$hours = floor($tn["time"] / 3600);
		$mins = floor(($tn["time"] - ($hours*3600)) / 60);
		$secs = floor($tn["time"] % 60);



		echo '<tr class="summaryTnRow" data-tn_id="'. $tn ["tn_id"] .'" data-customer_id="'. $tn ["cust_id"] .'"  data-customer_name="'. $tn ["name"] .'" data-tn_date="'. $tn ["date"] .'" >';
		echo '<td>' . $tn ["name"] . '</td>';
		echo '<td>' . $tn ["tn_id"] . '</td>';
		echo '<td>' . $tn ["text"] . '</td>';
		echo '<td>' . $tn ["date"] . '</td>';
		echo '<td class="summary_time">'.sprintf('%02d',$hours).':'.sprintf('%02d',$mins).':'.sprintf('%02d',$secs). '</td>';
		echo '<td><input type="button" class="summaryDelBtn" value="L&ouml;schen" ></td>';
		echo '</tr>';
	}
	?>
	</table>
	</div>
	</div>
	<div id="status">
	<span> Letzter Abgleich: </span><span id="lastSync"></span>
	</div>
	<div id="footerBar">
		<a href="<?php echo $CONTEXT_PATH ?>/changelog.php" target="blank">Changelog</a>
	</div>
</body>
<script type="text/javascript">

	function refreshCustomerList(data,name){
		$("#newCust").before("<option value='"+data+"'>"+name+"</option>");
	};

	$("document").ready(function(){
		 $( "#dialog-form" ).dialog({
			 autoOpen: false,
			 height: 300,
			 width: 350,
			 modal: true,
			 buttons: {
				 "OK": function() {
					//Mit funktion f&uuml;llen
				 	
				 	addNewCustomer($("#newCustName").val());
				 },
				 Cancel: function() {
					 $( this ).dialog( "close" );
				 }
			 },
			 close: function() {
				 //Mit funktion f&uuml;llen
			 }
			});

		$("#newCust").click(function(){
			 $( "#dialog-form" ).dialog( "open" );	
		});

		var x = new tnManager(<?php  echo json_encode($activeTnArray) ?>);
	});








	function createTd(content){
		return $("<td></td>").append(content);
	};
	
	function rowTemplate(tn,customer,starttime){
		return  "<tr>"+
				"<td>"+currentMaxId+"</td>"+
			   	"<td><span id='kunde_"+currentMaxId+"' >"+cust+"</span></td>"+
			   	"<td><textarea name='tat"+currentMaxId+"' id='tat"+currentMaxId+"' ></textarea></td>"+
			   	"<td><span id='starttime_"+currentMaxId+"'' >"+starttime+"'</span></td>"+
			   	"<td><span id='endtime_"+currentMaxId+"'  >"+starttime+"'</span></td>"+
			   	"<td><input data-tn_id='"+tn+"' data-customer_id='"+custid+"' name='amount_"+currentMaxId+"' id='amount_"+currentMaxId+"' value='' /></td>"+
			   	"<td><input type='button'  name='calcSum_"+currentMaxId+"' id='calcSum_"+currentMaxId+"' value='Summe' onclick='calculateCustomerSum("+currentMaxId+")' /></td>"+
			   	"</tr>";		
	};




</script>


<div id="dialog-form" title="Neuen Kunden hinzuf&uuml;gen">
	<label for="name">Name</label> <input type="text" name="name"
		id="newCustName" class="text ui-widget-content ui-corner-all">
</div>
</html>